server:
  port: 8888


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp
  jpa:
    generate-ddl: false #auto DDL ?? off
    show-sql: true # ??? ?? ????
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true # ?? ??? ?? ?? ??

# ????? ?? info? ???? debug? ?? ??? ?? ??
logging:
  level:
    com:
      ohgiraffers:
        springdatajpa: debug